### ISSUE TITLE
How to deactivate sidebar?

### ISSUE THREAD

**Issue by andreabisello** [Codeinwp/roda#3]
Hi
i'm using your theme in my new website http://www.tablesoccerfriends.com . I don't want to see sidebar in mobile mobile. How to deactivate it?

thanks.

**Comment by rodica-andronache** [comment]
Hi,

Unfortunately this option is not available in the theme , you can try with some custom css maybe to hide the button that opens the sidebar with the sidebar-toggle class on mobile devices with @media query
